# Generated by Django 5.0.3 on 2024-06-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
